I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 923, in script
    Lay "WE GOTTA SHUT THE PLACE DOWN."
Exception: Sayer 'lay' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 923, in script
    Lay "WE GOTTA SHUT THE PLACE DOWN."
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\chris\Downloads\renpy-7.4.5-sdk/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'lay' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.6.1693
The Average Day in L'stanberg 1.0
Sun Oct  3 16:57:47 2021
